### assumes ubuntu image
---
- name: update apt cache
  apt: update_cache=yes
  become: true

- name: install packages
  apt: 
      pkg: 
          - curl
          - build-essential
          - git
          - pkg-config
      state: latest
  become: true

- name: create directory
  file:
    path: "{{ home }}/genome_tools"
    state: directory
    mode: 0775

- name: clone the Tool_1 repository
  git:
    repo: https://github.com/volac-genomics/Tool_1.git
    version: main
    dest: "{{ home }}/genome_tools/Tool_1"

- name: clone the Tool_2 repository
  git:
    repo: https://github.com/volac-genomics/Tool_2.git
    version: main
    dest: "{{ home }}/genome_tools/Tool_2"

- name: clone the Tool_3 repository
  git:
    repo: https://github.com/volac-genomics/Tool_3.git
    version: main
    dest: "{{ home }}/genome_tools/Tool_3"

- name: install nextflow
  include_tasks: nextflow.yml

- name: install docker
  include_tasks: docker.yml

- name: install singularity
  include_tasks: singularity.yml
