name: ansible-ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          options: |
            --verbose

      - name: test Tool_1
        working-directory: /home/runner/genome_tools/Tool_1
        run: |
          wget -O input_tool1/test.fa https://www.ebi.ac.uk/ena/browser/api/fasta/GCA_002849515.1
          nextflow run tool_1.nf -profile ghactions
